controller_list:
  - name: fake_arm_controller
    joints:
      - j2s7s000_joint_1
      - j2s7s000_joint_2
      - j2s7s000_joint_3
      - j2s7s000_joint_4
      - j2s7s000_joint_5
      - j2s7s000_joint_6
      - j2s7s000_joint_7